/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionRappelInstruction extends PInstruction
{
    private PInstructionRappel _instructionRappel_;

    public AInstructionRappelInstruction()
    {
        // Constructor
    }

    public AInstructionRappelInstruction(
        @SuppressWarnings("hiding") PInstructionRappel _instructionRappel_)
    {
        // Constructor
        setInstructionRappel(_instructionRappel_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionRappelInstruction(
            cloneNode(this._instructionRappel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionRappelInstruction(this);
    }

    public PInstructionRappel getInstructionRappel()
    {
        return this._instructionRappel_;
    }

    public void setInstructionRappel(PInstructionRappel node)
    {
        if(this._instructionRappel_ != null)
        {
            this._instructionRappel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionRappel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionRappel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionRappel_ == child)
        {
            this._instructionRappel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionRappel_ == oldChild)
        {
            setInstructionRappel((PInstructionRappel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
