/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionVideInstruction extends PInstruction
{
    private PInstructionVide _instructionVide_;

    public AInstructionVideInstruction()
    {
        // Constructor
    }

    public AInstructionVideInstruction(
        @SuppressWarnings("hiding") PInstructionVide _instructionVide_)
    {
        // Constructor
        setInstructionVide(_instructionVide_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionVideInstruction(
            cloneNode(this._instructionVide_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionVideInstruction(this);
    }

    public PInstructionVide getInstructionVide()
    {
        return this._instructionVide_;
    }

    public void setInstructionVide(PInstructionVide node)
    {
        if(this._instructionVide_ != null)
        {
            this._instructionVide_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionVide_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionVide_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionVide_ == child)
        {
            this._instructionVide_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionVide_ == oldChild)
        {
            setInstructionVide((PInstructionVide) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
