/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionAffectationInstruction extends PInstruction
{
    private PInstructionAffectation _instructionAffectation_;

    public AInstructionAffectationInstruction()
    {
        // Constructor
    }

    public AInstructionAffectationInstruction(
        @SuppressWarnings("hiding") PInstructionAffectation _instructionAffectation_)
    {
        // Constructor
        setInstructionAffectation(_instructionAffectation_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionAffectationInstruction(
            cloneNode(this._instructionAffectation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionAffectationInstruction(this);
    }

    public PInstructionAffectation getInstructionAffectation()
    {
        return this._instructionAffectation_;
    }

    public void setInstructionAffectation(PInstructionAffectation node)
    {
        if(this._instructionAffectation_ != null)
        {
            this._instructionAffectation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionAffectation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionAffectation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionAffectation_ == child)
        {
            this._instructionAffectation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionAffectation_ == oldChild)
        {
            setInstructionAffectation((PInstructionAffectation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
