/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionSiInstruction extends PInstruction
{
    private PInstructionSi _instructionSi_;

    public AInstructionSiInstruction()
    {
        // Constructor
    }

    public AInstructionSiInstruction(
        @SuppressWarnings("hiding") PInstructionSi _instructionSi_)
    {
        // Constructor
        setInstructionSi(_instructionSi_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionSiInstruction(
            cloneNode(this._instructionSi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionSiInstruction(this);
    }

    public PInstructionSi getInstructionSi()
    {
        return this._instructionSi_;
    }

    public void setInstructionSi(PInstructionSi node)
    {
        if(this._instructionSi_ != null)
        {
            this._instructionSi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionSi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionSi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionSi_ == child)
        {
            this._instructionSi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionSi_ == oldChild)
        {
            setInstructionSi((PInstructionSi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
