/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionRetourInstruction extends PInstruction
{
    private PInstructionRetour _instructionRetour_;

    public AInstructionRetourInstruction()
    {
        // Constructor
    }

    public AInstructionRetourInstruction(
        @SuppressWarnings("hiding") PInstructionRetour _instructionRetour_)
    {
        // Constructor
        setInstructionRetour(_instructionRetour_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionRetourInstruction(
            cloneNode(this._instructionRetour_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionRetourInstruction(this);
    }

    public PInstructionRetour getInstructionRetour()
    {
        return this._instructionRetour_;
    }

    public void setInstructionRetour(PInstructionRetour node)
    {
        if(this._instructionRetour_ != null)
        {
            this._instructionRetour_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionRetour_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionRetour_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionRetour_ == child)
        {
            this._instructionRetour_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionRetour_ == oldChild)
        {
            setInstructionRetour((PInstructionRetour) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
