/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionTantqueInstruction extends PInstruction
{
    private PInstructionTantque _instructionTantque_;

    public AInstructionTantqueInstruction()
    {
        // Constructor
    }

    public AInstructionTantqueInstruction(
        @SuppressWarnings("hiding") PInstructionTantque _instructionTantque_)
    {
        // Constructor
        setInstructionTantque(_instructionTantque_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionTantqueInstruction(
            cloneNode(this._instructionTantque_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionTantqueInstruction(this);
    }

    public PInstructionTantque getInstructionTantque()
    {
        return this._instructionTantque_;
    }

    public void setInstructionTantque(PInstructionTantque node)
    {
        if(this._instructionTantque_ != null)
        {
            this._instructionTantque_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instructionTantque_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instructionTantque_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instructionTantque_ == child)
        {
            this._instructionTantque_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instructionTantque_ == oldChild)
        {
            setInstructionTantque((PInstructionTantque) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
