/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AParanthesesExp7 extends PExp7
{
    private TParantheseOuvrante _parantheseOuvrante_;
    private PExpression _expression_;
    private TParantheseFermante _parantheseFermante_;

    public AParanthesesExp7()
    {
        // Constructor
    }

    public AParanthesesExp7(
        @SuppressWarnings("hiding") TParantheseOuvrante _parantheseOuvrante_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") TParantheseFermante _parantheseFermante_)
    {
        // Constructor
        setParantheseOuvrante(_parantheseOuvrante_);

        setExpression(_expression_);

        setParantheseFermante(_parantheseFermante_);

    }

    @Override
    public Object clone()
    {
        return new AParanthesesExp7(
            cloneNode(this._parantheseOuvrante_),
            cloneNode(this._expression_),
            cloneNode(this._parantheseFermante_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParanthesesExp7(this);
    }

    public TParantheseOuvrante getParantheseOuvrante()
    {
        return this._parantheseOuvrante_;
    }

    public void setParantheseOuvrante(TParantheseOuvrante node)
    {
        if(this._parantheseOuvrante_ != null)
        {
            this._parantheseOuvrante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parantheseOuvrante_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public TParantheseFermante getParantheseFermante()
    {
        return this._parantheseFermante_;
    }

    public void setParantheseFermante(TParantheseFermante node)
    {
        if(this._parantheseFermante_ != null)
        {
            this._parantheseFermante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parantheseFermante_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parantheseOuvrante_)
            + toString(this._expression_)
            + toString(this._parantheseFermante_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parantheseOuvrante_ == child)
        {
            this._parantheseOuvrante_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._parantheseFermante_ == child)
        {
            this._parantheseFermante_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parantheseOuvrante_ == oldChild)
        {
            setParantheseOuvrante((TParantheseOuvrante) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._parantheseFermante_ == oldChild)
        {
            setParantheseFermante((TParantheseFermante) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
