/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ASansparamAppelfonction extends PAppelfonction
{
    private TIdentifiant _identifiant_;
    private TParantheseOuvrante _parantheseOuvrante_;
    private TParantheseFermante _parantheseFermante_;

    public ASansparamAppelfonction()
    {
        // Constructor
    }

    public ASansparamAppelfonction(
        @SuppressWarnings("hiding") TIdentifiant _identifiant_,
        @SuppressWarnings("hiding") TParantheseOuvrante _parantheseOuvrante_,
        @SuppressWarnings("hiding") TParantheseFermante _parantheseFermante_)
    {
        // Constructor
        setIdentifiant(_identifiant_);

        setParantheseOuvrante(_parantheseOuvrante_);

        setParantheseFermante(_parantheseFermante_);

    }

    @Override
    public Object clone()
    {
        return new ASansparamAppelfonction(
            cloneNode(this._identifiant_),
            cloneNode(this._parantheseOuvrante_),
            cloneNode(this._parantheseFermante_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASansparamAppelfonction(this);
    }

    public TIdentifiant getIdentifiant()
    {
        return this._identifiant_;
    }

    public void setIdentifiant(TIdentifiant node)
    {
        if(this._identifiant_ != null)
        {
            this._identifiant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifiant_ = node;
    }

    public TParantheseOuvrante getParantheseOuvrante()
    {
        return this._parantheseOuvrante_;
    }

    public void setParantheseOuvrante(TParantheseOuvrante node)
    {
        if(this._parantheseOuvrante_ != null)
        {
            this._parantheseOuvrante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parantheseOuvrante_ = node;
    }

    public TParantheseFermante getParantheseFermante()
    {
        return this._parantheseFermante_;
    }

    public void setParantheseFermante(TParantheseFermante node)
    {
        if(this._parantheseFermante_ != null)
        {
            this._parantheseFermante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parantheseFermante_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifiant_)
            + toString(this._parantheseOuvrante_)
            + toString(this._parantheseFermante_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifiant_ == child)
        {
            this._identifiant_ = null;
            return;
        }

        if(this._parantheseOuvrante_ == child)
        {
            this._parantheseOuvrante_ = null;
            return;
        }

        if(this._parantheseFermante_ == child)
        {
            this._parantheseFermante_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifiant_ == oldChild)
        {
            setIdentifiant((TIdentifiant) newChild);
            return;
        }

        if(this._parantheseOuvrante_ == oldChild)
        {
            setParantheseOuvrante((TParantheseOuvrante) newChild);
            return;
        }

        if(this._parantheseFermante_ == oldChild)
        {
            setParantheseFermante((TParantheseFermante) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
