/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.lexer;

@SuppressWarnings("serial")
public interface IPushbackReader
{
    public int read() throws IOException;
    public void unread(int c) throws IOException;
}
